# config.yaml
---
###
# train mode
###
mode: train
lr: !!float 1e-4
lr_backbone: !!float 1e-5
batch_size: 10
weight_decay: !!float 1e-4
epochs: 300
lr_drop: 200
clip_max_norm: 0.1
# model parameters
frozen_weights: Null
# backbone
backbone: resnet50
dilation: False
position_embedding: sine
# transformer
enc_layers: 6
dec_layers: 6
dim_feedforward: 2048
hidden_dim: 256
dropout: 0.1
nheads: 8
num_queries: 10
pre_norm: False
# loss
aux_loss: True
# matcher
set_cost_class: 1.
set_cost_bbox: 5.
set_cost_giou: 5.
# loss coefficeints
dice_loss_coef: 1.
bbox_loss_coef: 5.
giou_loss_coef: 5.
eos_coef: 0.1
# dataset parameters
train_dir: ../train
output_dir: ./output
scaled_width: 800
scaled_height: 800
num_class: 10
device: 'cuda'
seed: 42
resume: False
start_epoch: 0
num_workers: 3
---
###
# evaluate mode
###
mode: eval
# backbone
backbone: resnet50
dilation: False
position_embedding: sine
# transformer
enc_layers: 6
dec_layers: 6
dim_feedforward: 2048
hidden_dim: 256
dropout: 0.1
nheads: 8
num_queries: 10
pre_norm: False
# dataset parameters
scaled_width: 800
scaled_height: 800
device: 'cuda'
classes:
  - Ban
  - BanLeft
  - BanRight
  - BanStright
  - Bee
  - TurnLeft
  - TurnRight
  - GoStright
  - Park
  - Stop
colors:
  -
    - 0.000
    - 0.447
    - 0.741
  -
    - 0.850
    - 0.325
    - 0.098
  -
    - 0.929
    - 0.694
    - 0.125
  -
    - 0.494
    - 0.184
    - 0.556
  -
    - 0.466
    - 0.674
    - 0.188
  -
    - 0.301
    - 0.745
    - 0.933